// Generated by CoffeeScript 1.3.3
(function() {
  var NextFlow, next,
    __bind = function(fn, me){ return function(){ return fn.apply(me, arguments); }; };

  NextFlow = (function() {

    function NextFlow(nextObject) {
      var key, val, _ref,
        _this = this;
      this.nextObject = nextObject;
      this.next = __bind(this.next, this);

      this.keys = [];
      this.funcs = [];
      this.current = null;
      _ref = this.nextObject;
      for (key in _ref) {
        val = _ref[key];
        if (this.nextObject.hasOwnProperty(key)) {
          this.keys.push(key);
          this.funcs.push(val);
          (function(key, val) {
            return _this[key] = function() {
              this.current = key;
              return val.apply(this, arguments);
            };
          })(key, val);
        }
      }
    }

    NextFlow.prototype.next = function() {
      var idx;
      if (this.current === null) {
        this.current = this.keys[0];
        return this.funcs[0].apply(this, arguments);
      } else {
        idx = this.keys.indexOf(this.current);
        idx += 1;
        this.current = this.keys[idx];
        return this.funcs[idx].apply(this, arguments);
      }
    };

    return NextFlow;

  })();

  next = function(nextObject) {
    var nf;
    nf = new NextFlow(nextObject);
    return nf.next();
  };

  module.exports = next;

}).call(this);
